# Generated by Django 5.1.7 on 2025-03-21 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'unidade', 'verbose_name_plural': 'unidades'},
        ),
        migrations.AlterModelTable(
            name='branch',
            table='branch',
        ),
    ]
