# Generated by Django 5.1.7 on 2025-03-26 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time',
            field=models.CharField(blank=True, choices=[('1', '06:00'), ('2', '07:00'), ('3', '08:00'), ('4', '09:00'), ('5', '10:00'), ('6', '11:00'), ('7', '12:00'), ('8', '13:00'), ('9', '14:00'), ('10', '15:00'), ('11', '16:00'), ('12', '17:00'), ('13', '18:00'), ('14', '19:00'), ('15', '20:00'), ('16', '21:00')], default=None, max_length=2, null=True, verbose_name='horário'),
        ),
    ]
