# Generated by Django 5.1.7 on 2025-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('1', 'Domingo'), ('2', 'Segunda-feira'), ('3', 'Terça-feira'), ('4', 'Quarta-feira'), ('5', 'Quinta-feira'), ('6', 'Sexta-feira'), ('7', 'Sábado')], max_length=100, unique=True, verbose_name='nome')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'dia do treino',
                'verbose_name_plural': 'dias do treino',
                'db_table': 'training_day',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='frequency',
        ),
        migrations.AlterField(
            model_name='user',
            name='time',
            field=models.CharField(blank=True, choices=[('6', '06:00'), ('7', '07:00'), ('8', '08:00'), ('9', '09:00'), ('10', '10:00'), ('11', '11:00'), ('12', '12:00'), ('13', '13:00'), ('14', '14:00'), ('15', '15:00'), ('16', '16:00'), ('17', '17:00'), ('18', '18:00'), ('19', '19:00'), ('20', '20:00'), ('21', '21:00')], default=None, max_length=2, null=True, verbose_name='horário'),
        ),
        migrations.AddField(
            model_name='user',
            name='training_days',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='users', to='core.trainingday', verbose_name='dias do treino'),
        ),
    ]
