# Generated by Django 5.1.7 on 2025-03-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_professional'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='branch',
            new_name='branches',
        ),
    ]
