# Generated by Django 5.1.7 on 2025-03-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_trainingday_remove_user_frequency_alter_user_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='training_days',
            field=models.ManyToManyField(related_name='users', to='core.trainingday', verbose_name='dias do treino'),
        ),
    ]
