# Generated by Django 5.1.7 on 2025-03-21 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_branch_professional_branches'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professional',
            options={'ordering': ['user__first_name', 'user__last_name'], 'verbose_name': 'profissional', 'verbose_name_plural': 'profissionais'},
        ),
    ]
