# Generated by Django 5.1.7 on 2025-03-21 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0006_alter_professional_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='role',
        ),
        migrations.AddField(
            model_name='professional',
            name='groups',
            field=models.ManyToManyField(related_name='professionals', related_query_name='professional', to='auth.group', verbose_name='grupos'),
        ),
    ]
