# Generated by Django 5.1.7 on 2025-03-21 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_professional_role_professional_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='groups',
        ),
    ]
