# Generated by Django 5.1.7 on 2025-03-21 22:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='branches',
            field=models.ManyToManyField(related_name='clients', related_query_name='client', to='core.branch', verbose_name='unidades'),
        ),
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='telefone'),
        ),
    ]
