# Generated by Django 5.1.7 on 2025-03-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_client_branches_alter_client_cpf_alter_client_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='frequency',
            field=models.CharField(choices=[(1, '1x por semana'), (2, '2x por semana'), (3, '3x por semana'), (5, '5x por semana')], default=1, max_length=1, verbose_name='frequência'),
        ),
    ]
